import {describe, it, expect} from 'vitest';
import {
	emitCi,
	githubCiProvider,
	CI_SYSTEMS,
	type EmitCiInput,
} from '../../src/ci/ci-emit.js';

/**
 * The CI emitter is a PURE function of its input (no filesystem, no network):
 * it returns the workflow file (path + contents) and the required repo
 * secrets/vars report. The command layer / CLI wrapper is the thing that
 * writes the file to disk and prints the report — that boundary keeps this
 * unit test hermetic (assert the STRING, snapshot-locked, and the report).
 */

/** A representative two-node ipns site (publisher first) — the common case. */
function baseInput(overrides: Partial<EmitCiInput> = {}): EmitCiInput {
	return {
		system: 'github',
		buildCommand: 'npm run build',
		outputDir: 'dist',
		...overrides,
	};
}

describe('emitCi — CIProvider seam', () => {
	it('emits GitHub Actions as the first (v1) implementation', () => {
		const result = emitCi(baseInput());
		expect(result.system).toBe('github');
		expect(result.workflow.path).toBe('.github/workflows/pinnace-deploy.yml');
	});

	it('lists exactly `github` as the only v1 CI system', () => {
		expect(CI_SYSTEMS).toEqual(['github']);
	});

	it('rejects an unimplemented CI system loudly (the seam exists, impls do not)', () => {
		expect(() => emitCi(baseInput({system: 'gitlab' as never}))).toThrow(
			/gitlab/i,
		);
	});

	it('reports the required repo secrets and vars (multi-node contract)', () => {
		const result = emitCi(baseInput());

		// IPFS_TOKEN is the ONLY secret (comma-separated tokens, publisher first).
		expect(result.secrets.map((s) => s.name)).toEqual(['IPFS_TOKEN']);
		const token = result.secrets[0]!;
		expect(token.multiNode).toBe(true);
		expect(token.description).toMatch(/comma-separated/i);
		expect(token.description).toMatch(/publisher first/i);

		// The rest are (non-secret) repo variables.
		expect(result.vars.map((v) => v.name)).toEqual([
			'IPFS_API',
			'SITE_NAME',
			'SITE_MODE',
		]);
		const api = result.vars.find((v) => v.name === 'IPFS_API')!;
		expect(api.multiNode).toBe(true);
		expect(api.description).toMatch(/comma-separated/i);
		expect(api.description).toMatch(/publisher first/i);
	});

	it('snapshots the generated GitHub Actions workflow', () => {
		const result = emitCi(baseInput());
		expect(result.workflow.contents).toMatchInlineSnapshot(`
			"# =============================================================================
			# pinnace: deploy a static site to your self-hosted IPFS node(s) on push.
			#
			# Generated by \`pinnace install-ci --system github\`. Edit BUILD/OUTPUT below
			# for your stack; the deploy step is owned by the \`pinnace\` CLI.
			#
			# Set these in your repo (Settings -> Secrets and variables -> Actions):
			#   IPFS_API    (variable) one URL, OR comma-separated for MULTIPLE nodes,
			#               publisher first (e.g. https://ipfs-a.you.com,https://ipfs-b.you.com)
			#   IPFS_TOKEN  (secret)   matching token(s), comma-separated in the SAME order
			#   SITE_NAME   (variable) e.g. mysite.eth
			#   SITE_MODE   (variable) ipfs | ipns  (default ipns)
			#
			# Multiple nodes serve the SAME CID (redundancy). In ipns mode the PUBLISHER
			# (first in IPFS_API) publishes the signed record; replicas mirror it.
			# =============================================================================
			name: Deploy to IPFS

			on:
			  push:
			    branches: [main]
			  workflow_dispatch: {}

			concurrency:
			  group: pinnace-deploy
			  cancel-in-progress: true

			jobs:
			  deploy:
			    runs-on: ubuntu-latest
			    steps:
			      - uses: actions/checkout@v4

			      - uses: actions/setup-node@v4
			        with:
			          node-version: 20
			          cache: npm

			      - name: Install deps
			        run: npm ci

			      - name: Build
			        run: npm run build

			      - name: Deploy to IPFS node(s)
			        id: deploy
			        env:
			          IPFS_API: \${{ vars.IPFS_API }}
			          IPFS_TOKEN: \${{ secrets.IPFS_TOKEN }}
			          SITE_NAME: \${{ vars.SITE_NAME }}
			          SITE_MODE: \${{ vars.SITE_MODE || 'ipns' }}
			        run: |
			          npx pinnace deploy --set-mode "$SITE_MODE" "dist" "$SITE_NAME"

			      - name: Summary
			        if: always()
			        run: |
			          echo "### IPFS deploy" >> "$GITHUB_STEP_SUMMARY"
			          echo "" >> "$GITHUB_STEP_SUMMARY"
			          echo "- CID:  \\\`\${{ steps.deploy.outputs.cid }}\\\`" >> "$GITHUB_STEP_SUMMARY"
			          echo "- IPNS: \\\`\${{ steps.deploy.outputs.ipns }}\\\`" >> "$GITHUB_STEP_SUMMARY"
			          echo "- Preview: https://\${{ steps.deploy.outputs.cid }}.ipfs.dweb.link/" >> "$GITHUB_STEP_SUMMARY"
			"
		`);
	});

	it('honours a custom build command / output dir in the workflow', () => {
		const result = emitCi(
			baseInput({buildCommand: 'pnpm build', outputDir: 'build'}),
		);
		expect(result.workflow.contents).toContain('pnpm build');
		expect(result.workflow.contents).toContain('build');
	});

	it('workflow wires the multi-node env contract into the deploy step', () => {
		const {contents} = emitCi(baseInput()).workflow;
		// The deploy step reads the same env the deploy core consumes:
		// IPFS_API/IPFS_TOKEN are comma-separated (publisher first), plus
		// SITE_NAME + SITE_MODE. IPFS_TOKEN comes from secrets, the rest vars.
		expect(contents).toContain('IPFS_API: ${{ vars.IPFS_API }}');
		expect(contents).toContain('IPFS_TOKEN: ${{ secrets.IPFS_TOKEN }}');
		expect(contents).toContain('SITE_NAME: ${{ vars.SITE_NAME }}');
		expect(contents).toMatch(
			/SITE_MODE: \$\{\{ vars\.SITE_MODE \|\| 'ipns' \}\}/,
		);
		// per-site mode: publisher publishes, replicas mirror the same CID.
		expect(contents).toMatch(/pinnace deploy/);
	});

	it('githubCiProvider is the same emitter reachable directly via the seam', () => {
		const viaSeam = githubCiProvider.emit(baseInput());
		const viaDispatch = emitCi(baseInput());
		expect(viaSeam.workflow.contents).toBe(viaDispatch.workflow.contents);
		expect(viaSeam.secrets).toEqual(viaDispatch.secrets);
		expect(viaSeam.vars).toEqual(viaDispatch.vars);
	});
});
